encyclopedia/urls.py
from django.urls import path

from . import views

app_name = "wiki"
urlpatterns = [
    path("", views.index, name="index"),
    path("<str:title>", views.entry, name="entry"),
    path("search/", views.search, name="search"),
    path("new/", views.new, name="new"),
    path("edit/", views.edit, name="edit"),
    path("update/", views.update, name="update"),
    path("randomSelect/", views.randomSelect, name="randomSelect"),
]

wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('wiki/', include("encyclopedia.urls"))
]

encyclopedia/models.py
from django.db import models

# Create your models here.

encyclopedia/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
import random
import html2text
from markdown2 import Markdown

from . import util

# Convert makrdown to HTML
markdowner = Markdown()

def index(request):
    return render(request, "encyclopedia/index.html", {
        "entries": util.list_entries(),
    })


#  Display the contents of that encyclopedia entry
def entry(request, title):

    # Render 404 error if the requested entry does not exist
    if util.get_entry(title) == None:
        return render(request, "encyclopedia/error.html", {
            "message": "The entry's page you requested is not available. Please try a valid one."
        })
    else:
        # Get entry content using util function
        content = util.get_entry(title)
        
        # Render the content entry if it does exist
        return render(request, "encyclopedia/page.html", {
            "title": title,
            "content": markdowner.convert(content)
        })
    
    
# Search feature
def search(request):
    # store the input value
    query = request.GET.get("q")

    # Check if the query is empty
    if not query:
        return HttpResponseRedirect(reverse("wiki:index"))
    
    # Go to search result
    if util.get_entry(query) == None:
        list = []
        # Check the title substring
        for entry in util.list_entries():
            if query.lower() in entry.lower():
                list.append(entry)

        return render(request, "encyclopedia/search.html",{
            "list": list
        })

    # Query match, Redirect to the entry's page
    return HttpResponseRedirect(reverse("wiki:entry", args=[query]))
        
    
# Create New Page
def new(request):
    if request.method == "POST":

        # store form values
        title = request.POST.get("title")
        content = request.POST.get("content")

        # Check if fields are empty
        if not title or not content:
            return HttpResponseRedirect(reverse('wiki:new'))
        
        # Show error message if the entry aleady exist
        if util.get_entry(title) != None:
            return render(request, "encyclopedia/error.html", {
                "message": "This entry is already exist"
            })
        
        # Save the entry to disk
        util.save_entry(title, content)

        # Take the user to the new page
        return HttpResponseRedirect(reverse("wiki:entry", args=[title]))

    return render(request, 'encyclopedia/new.html')


# Pass Through the entry information to the edit page
def edit(request):
    title = request.POST.get("title")
    content = request.POST.get("content")
    
    return render(request, "encyclopedia/edit.html", {
        # Convert HTML to Markdown
        "content": html2text.html2text(content),
        "title": title
    })


# update Page
def update(request):
    if request.method == "POST":
        title = request.POST.get("title")
        content = request.POST.get("content")

        # Save the changes
        util.save_entry(title, content)

        # Redirected to entry's page
        return HttpResponseRedirect(reverse("wiki:entry", args=[title]))

    return render(request, "encyclopedia/edit.html", {
        "content": content
    })


# Select random entry
def randomSelect(request):
    entries = util.list_entries()
    
    # Number of elements to randomly select
    k = 1

    # Select k random elements from the list
    title = random.sample(entries, k)[0]

    return HttpResponseRedirect(reverse("wiki:entry", args=[title]))

encyclopedia/templates/encyclopedia/edit.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
  Edit
{% endblock %}

{% block body %}
  <h2 class="mt-3">Edit your content</h2>
  <div class="row">
    <div class="col-12 col-md-10 col-lg-10">
      <form action="{% url 'wiki:update' %}" class="mt-3" method="post">
        {% csrf_token %}
        <input type="hidden" name="title" value="{{ title }}">
        <div class="form-group">
          <textarea class="form-control" id="w3review" name="content" rows="20"
            placeholder="Describe your encyclopedia content...">{{ content }}</textarea>
        </div>
        <button type="submit" class="btn btn-primary">Save</button>
      </form>
    </div>
  </div>
{% endblock %}

encyclopedia/templates/encyclopedia/error.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    404 error
{% endblock %}

{% block body %}
    <h1>{{ message }}</h1>
    <a href="{% url 'wiki:index' %}">Take me home</a>
{% endblock %}

encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>All Pages</h1>

    <ul>
        {% for entry in entries %}
            <li><a href="{{ entry }}">{{ entry }}</a></li>
        {% endfor %}
    </ul>
{% endblock %}

encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <div class="row">
            <div class="sidebar col-lg-2 col-md-3">
                <h2>Wiki</h2>
                <form action="{% url 'wiki:search' %}" action="get">
                    <input class="search" type="text" name="q" placeholder="Search Encyclopedia">
                </form>
                <div>
                    <a href="{% url 'wiki:index' %}">Home</a>
                </div>
                <div>
                    <a href="{% url 'wiki:new' %}">Create New Page</a>
                </div>
                <div>
                    <a href="{% url 'wiki:randomSelect' %}">Random Page</a>
                </div>
                {% block nav %}
                {% endblock %}
            </div>
            <div class="main col-lg-10 col-md-9">
                {% block body %}
                {% endblock %}
            </div>
        </div>

    </body>
</html>

encyclopedia/templates/encyclopedia/new.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Create New Page
{% endblock %}

{% block body %}
  <h2 class="mt-3">Create new entry's page</h2>
  <div class="row">
    <div class="col-12 col-md-8">
        <form action="{% url 'wiki:new' %}" class="mt-3" method="post">
            {% csrf_token %}
            <div class="form-group">
                <input autocomplete="none" autofocus type="text" class="form-control" name="title" placeholder="Encyclopedia Name">
            </div>
            <div class="form-group">
                <textarea class="form-control" id="w3review" name="content" rows="15" placeholder="Describe your encyclopedia content..."></textarea>
            </div>
            <button type="submit" class="btn btn-primary">Save</button>
        </form>
    </div>
  </div>
{% endblock %}

encyclopedia/templates/encyclopedia/page.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
  {{ title }}
{% endblock %}

{% block body %}
  <div class="ml-4">
    <div>
      {{ content|safe }}
    </div>

    <!-- Pass Through the entry information to the edit page -->
    <form action="{% url 'wiki:edit' %}" method="post">
      {% csrf_token %}
      <input type="hidden" name="title" value="{{ title }}">
      <input type="hidden" name="content" value="{{ content }}">
      <input type="submit" value="Edit" class="btn btn-primary mt-3">
    </form>
  </div>
{% endblock %}

encyclopedia/templates/encyclopedia/search.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Search results
{% endblock %}

{% block body %}
    <h1>Search Results</h1>
    <p>Did you mean: </p>
    
    <ul>
        {% for entry in list %}
            <li><a href="{% url 'wiki:entry' entry %}">{{ entry }}</a></li>
        {% endfor %}
    </ul>
{% endblock %}